// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRsIysc_64se7epiilujqiUmfpsNJc9o',
    appId: '1:746746575503:web:4e7e9f82f58b939eb78efa',
    messagingSenderId: '746746575503',
    projectId: 'fitnessapp-b20e9',
    authDomain: 'fitnessapp-b20e9.firebaseapp.com',
    storageBucket: 'fitnessapp-b20e9.appspot.com',
    measurementId: 'G-NR2YHHMWS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNOMLDhvoGtL-1WDT6WTKup3g4pWw9Rk',
    appId: '1:746746575503:android:e28810a47198f5c7b78efa',
    messagingSenderId: '746746575503',
    projectId: 'fitnessapp-b20e9',
    storageBucket: 'fitnessapp-b20e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMiSBFOB1XSx2N4lbr39WbnaI6vP49OyQ',
    appId: '1:746746575503:ios:6d6b33298c866891b78efa',
    messagingSenderId: '746746575503',
    projectId: 'fitnessapp-b20e9',
    storageBucket: 'fitnessapp-b20e9.appspot.com',
    iosClientId:
        '746746575503-o8pm00pubnai4buu6u0r4juuuv0s9mi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMiSBFOB1XSx2N4lbr39WbnaI6vP49OyQ',
    appId: '1:746746575503:ios:6d6b33298c866891b78efa',
    messagingSenderId: '746746575503',
    projectId: 'fitnessapp-b20e9',
    storageBucket: 'fitnessapp-b20e9.appspot.com',
    iosClientId:
        '746746575503-o8pm00pubnai4buu6u0r4juuuv0s9mi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
